DirectoryPath: "./exampleSite/public"
IgnoreURLs:
- "twitter.com"
CheckFavicon: true
EnforceHTML5: true
HTTPHeaders: {"Range": "bytes=0-0", "Accept": "*/*"}
IgnoreExternalBrokenLinks: false
LogLevel: 1