DirectoryPath: "./exampleSite/public"
CheckFavicon: false
EnforceHTML5: true
HTTPHeaders: {"Range": "bytes=0-0", "Accept": "*/*", "User-Agent": "HtmlTest/1.0.0"}
IgnoreExternalBrokenLinks: false
LogLevel: 0