# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo CRSU Theme Based on Hugo Bootstrap Theme"
license = "MIT"
licenselink = "https://github.com/CRSU-Apps/hugo-bootstrap-theme/blob/main/LICENSE"
description = "Custom Hugo Theme for CRSU based on Hugo Bootstrap Theme by Filipe Caneiro"

homepage = "https://github.com/CRSU-Apps/hugo-bootstrap-theme"
demosite = "https://apps.crsu.org.uk"

tags = ["bootstrap","minimal","responsive","modern","blog","landing page"]
features = ["security aware","fast by default","seo-ready","bootstrap framework","bootstrap 5","bootstrap 5.3"]

min_version = "0.99.1"

authors = [
  {name = "Filipe Carneiro", homepage = "https://github.com/filipecarneiro"},
  {name = "Ryan J Field", homepage = "www.ryanfield.me"}
]