baseURL = 'https://filipecarneiro.github.io/hugo-bootstrap-theme/'
title = "Hugo Bootstrap Theme"
author = "Filipe Carneiro"
copyright = "Open-source <a class=\"text-muted text-decoration-none\" href=\"https://github.com/filipecarneiro/hugo-bootstrap-theme/blob/main/LICENSE\">MIT</a> Licensed."

timeZone = 'Europe/London'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = "hugo-bootstrap-theme"
themesdir = "../.."

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = 'series'
  author = "authors"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"

defaultMarkdownHandler = "goldmark"

[goldmark]

  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

  [goldmark.parser]
    autoHeadingID = true
    wrapStandAloneImageWithinParagraph = false

    [goldmark.parser.attribute]
      block = true
      title = true

  [goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false

[tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2