[[main]]
name = "Home"
url = "/"
weight = 10

[[main]]
identifier = "services"
name = "Services"
url = "/services/"
weight = 30

[[main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 40

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" class=\"feather feather-github\"><use href=\"/images/feather-sprite.svg#github\"></path></svg>"
  url = "https://github.com/filipecarneiro/hugo-bootstrap-theme"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" class=\"feather feather-twitter\"><use href=\"/images/feather-sprite.svg#twitter\"></path></svg>"
  url = "https://twitter.com/jfilipecarneiro"
  weight = 20
